Repository myriadsocial/myriad-charts, pull requests merged in 2022-02, with the labels that each got.

#21 MYR-000: added myriad-cms new env
  charts/myriad-cms/templates/_helpers.tpl
  charts/myriad-cms/templates/deployment.yaml
  charts/myriad-cms/templates/secrets.yaml
  charts/myriad-cms/values.yaml
Labels: enhancement

#22 Changed CMS container port
  .github/workflows/tester.yml
  README.md
  charts/myriad-cms/templates/deployment.yaml
  ct.yaml
Labels: enhancement

#23 Removed CMS default security context
  charts/myriad-cms/values.yaml
Labels: enhancement

#24 Add new env myriad-web
  charts/myriad-web/templates/deployment.yaml
  charts/myriad-web/templates/secrets.yaml
  charts/myriad-web/values.yaml
Labels: enhancement

#25 MYRR-000: update .gitignore
  .gitignore
Labels: documentation

#26 add new env myriad-api
  charts/myriad-api/templates/_helpers.tpl
  charts/myriad-api/templates/deployment.yaml
  charts/myriad-api/templates/secrets.yaml
  charts/myriad-api/values.yaml
Labels: enhancement

#27 Fix deployment env myriad-api
  charts/myriad-api/templates/deployment.yaml
Labels: Fix
